### ISSUE TITLE
Incompatibility With Oculus Mod on Forge

### ISSUE THREAD

**Issue by ghost** [FiguraMC/Figura#176]
issue reported on Oculus github [here](https://github.com/Asek3/Oculus/issues/548)

```
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 15 more
Caused by: java.lang.ExceptionInInitializerError
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.resources.ResourceKey.m_135788_(ResourceKey.java:26)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.registries.Registries.m_257397_(Registries.java:200)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.registries.Registries.<clinit>(Registries.java:93)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.flag.FeatureElement.<clinit>(FeatureElement.java:18)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:45)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.Items.<clinit>(Items.java:21)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.ItemRenderer.<clinit>(ItemRenderer.java:51)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.RenderType.<clinit>(RenderType.java:101)
	at TRANSFORMER/figura@0.1.2+1.20.1/forge.org.figuramc.figura.model.rendering.texture.RenderTypes.<clinit>(RenderTypes.java:27)
	at TRANSFORMER/figura@0.1.2+1.20.1/forge.org.figuramc.figura.lua.docs.FiguraListDocs$2.<init>(FiguraListDocs.java:44)
	at TRANSFORMER/figura@0.1.2+1.20.1/forge.org.figuramc.figura.lua.docs.FiguraListDocs.<clinit>(FiguraListDocs.java:43)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.platform.InputConstants$Type.handler$gok000$addKey(InputConstants.java:515)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.platform.InputConstants$Type.m_84899_(InputConstants.java)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.platform.InputConstants$Type.<clinit>(InputConstants.java:214)
	at TRANSFORMER/oculus@1.6.15/net.coderbot.iris.Iris.<clinit>(Iris.java:95)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.SystemReport.handler$bhm000$fillSystemDetails(SystemReport.java:523)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.SystemReport.<init>(SystemReport.java:58)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.CrashReport.<init>(CrashReport.java:31)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.CrashReport.m_127529_(CrashReport.java:216)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:149)
	... 23 more
Caused by: java.lang.IllegalArgumentException: Not bootstrapped (called from registry ResourceKey[minecraft:root / minecraft:root])
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_179916_(Bootstrap.java:113)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_179912_(Bootstrap.java:106)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.MappedRegistry.<init>(MappedRegistry.java:85)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.MappedRegistry.<init>(MappedRegistry.java:81)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.registries.BuiltInRegistries.<clinit>(BuiltInRegistries.java:113)
	... 43 more
```

**Comment by UnlikePaladin** [comment]
um what the hell is oculus doing, are you sure it's oculus?

**Comment by ghost** [comment]
> um what the hell is oculus doing, are you sure it's oculus?

Yes it is Oculus and specifically only the last version. the one right before it worked fine.

**Comment by UnlikePaladin** [comment]
I've left a solution to the developer on their issue tracker, it is up to them to either fix it, or not, until they reply back you can use Optifine or wait for an official Iris port instead

**Comment by ghost** [comment]
> I've left a solution to the developer on their issue tracker, it is up to them to either fix it, or not, until they reply back you can use Optifine or wait for an official Iris port instead

From the smug way they were speaking to you, I very much doubt anything will be fixed even thought it's a simple fix.

**Comment by UnlikePaladin** [comment]
Yeah tbh they were kinda rude, but Iris will be getting an official port sometime soon anyway so it's best to wait for that

**Comment by itsloley** [comment]
i threw together a fix for this and PR'd it, hopefully it'll get merged ig, i'm kind of surprised there was that sort of behavior for a ~10 line fix but at least it annoyed me enough to just go do it myself

[here's my fork/branch](https://github.com/itsloley/Oculus/tree/figurafix) if anyone is interested in compiling this on their own, i only took a look at 1.20.1 since that's the version i personally needed but it works nonetheless. i haven't really done vigorous testing, but i haven't encountered absolutely any issues yet
