### ISSUE TITLE
[1.18.2] [Forge] Incompatability - More Player Models

### ISSUE THREAD

**Issue by Sybbyl0127** [FiguraMC/Figura#61]
Hear me out, I know MPM is basically the lite version of figure for ppl who cant model, but it is the most widely used option on Roleplay Servers, where FIgura would be a massive and exciting boon

The fact that we have Forge figura is AMAZING on its own, but MPM compatibility is the last thing keeping me from being able to freely use Figura on roleplay servers

I need to still be able to see other players MPM settings, when they don't have Figura, while I am using Figura. I'm fine with not using the MPM models/settings myself, I just need to be able to see them.

The following crash happens when only Figura & MorePlayerModels are loaded:

===========================================================================
---- Minecraft Crash Report ---- 
// Who set us up the TNT? 
 
Time: 8/13/23, 4:19 PM 
Description: Unexpected error 
 
java.lang.IllegalStateException: Pose stack not empty
 
	at net.minecraft.client.renderer.LevelRenderer.m_109588_(LevelRenderer.java:1419) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:forge-figura-common.mixins.json:render.LevelRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
 
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1225) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:forge-figura-common.mixins.json:render.LevelRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
 
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forge-figura-common.mixins.json:render.GameRendererAccessor,pl:mixin:APP:forge-figura-common.mixins.json:render.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
 
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forge-figura-common.mixins.json:render.GameRendererAccessor,pl:mixin:APP:forge-figura-common.mixins.json:render.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
 
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forge-figura-common.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
 
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forge-figura-common.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
 
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading,pl:runtimedistcleaner:A}
 
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
 
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
 
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
 
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
 
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.10.jar%2318!/:?] {}
 
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
 
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
 
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
 
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
 
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
 
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
 
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
 
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
 
 
 
A detailed walkthrough of the error, its code path and all known details is as follows: 
--------------------------------------------------------------------------------------- 
 
-- Head -- 
Thread: Render thread 
Stacktrace:
 
	at net.minecraft.client.renderer.LevelRenderer.m_109588_(LevelRenderer.java:1419) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:forge-figura-common.mixins.json:render.LevelRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
 
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1225) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:forge-figura-common.mixins.json:render.LevelRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
 
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forge-figura-common.mixins.json:render.GameRendererAccessor,pl:mixin:APP:forge-figura-common.mixins.json:render.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
 
-- Affected level -- 
Details: 
	All players: 1 total; [LocalPlayer['{MINECRAFT_USERNAME}'/71, l='ClientLevel', x=-0.50, y=-60.00, z=8.50]] 
	Chunk stats: 961, 609 
	Level dimension: minecraft:overworld 
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511) 
	Level time: 324 game time, 324 day time 
	Server brand: forge 
	Server type: Integrated singleplayer server 
Stacktrace:
 
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:forge-figura-common.mixins.json:ClientLevelInvoker,pl:mixin:A,pl:runtimedistcleaner:A}
 
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2264) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forge-figura-common.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
 
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:687) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forge-figura-common.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
 
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading,pl:runtimedistcleaner:A}
 
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
 
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
 
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
 
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
 
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.10.jar%2318!/:?] {}
 
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
 
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
 
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
 
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
 
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
 
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
 
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
 
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
 
 
 
-- Last reload -- 
Details: 
	Reload number: 1 
	Reload reason: initial 
	Finished: Yes 
	Packs: Default, Mod Resources, moreplayermodels

**Comment by alekso56** [comment]
This is a huge ask, these mods should be considered incompatible. im sorry.
